import { AgnosticPrice, ProductGetters, Attribute, ProductImage, ProductVariant } from "./../interfaces";
import { CatalogProduct, CatalogProductVariant } from "@kali604/reactioncommerce-api/lib/types/graphql";
export declare const getAttributes: (product: CatalogProduct) => Attribute[];
export declare const getVariantAttributes: (variant: ProductVariant) => Attribute[];
export declare const getPageTitle: (product: CatalogProduct) => string;
export declare const getTitle: (product: CatalogProduct) => string;
export declare const getDescription: (product: CatalogProduct) => string;
export declare const getSku: (variant: CatalogProductVariant) => string;
export declare const getId: (product: CatalogProduct) => string;
export declare const getSlug: (product: CatalogProduct) => string;
export declare const getMinOrderQuantity: (product: CatalogProduct | CatalogProductVariant) => number;
export declare const getVendor: (product: CatalogProduct) => string;
export declare const getDisplayPrice: (product: CatalogProduct | CatalogProductVariant, currencyCode: string) => string;
export declare const getPricing: (product: CatalogProduct | CatalogProductVariant, currencyCode: string) => AgnosticPrice;
export declare const getProductImages: (product: CatalogProduct) => ProductImage[];
export declare const getVariantImages: (variant: CatalogProductVariant) => ProductImage[];
export declare const getVariantSku: (variant: CatalogProductVariant) => string;
export declare const getProductVariants: (product: CatalogProduct) => ProductVariant[];
export declare const getInventory: (variant: CatalogProductVariant) => number;
declare const productGetters: ProductGetters<CatalogProduct, ProductVariant>;
export default productGetters;
